// GENERATED BY METAGEN

package com.rushingvise.metagen.sql;

public class ExpressionBuilder extends ExpressionBuilderApi.ExpressionStep {

    public ExpressionBuilder() {
        super(new ExpressionBuilderImpl.Content());
    }

}
