// GENERATED BY METAGEN

package com.rushingvise.metagen.sql;

public class QueryBuilder extends QueryBuilderApi.InitialStep {

    public QueryBuilder() {
        super(new QueryBuilderImpl.Content());
    }

}
