// GENERATED BY METAGEN

package com.rushingvise.metagen.sql;

public class QueryBuilderApi  {

    public interface ISelectTransition {
        QueryBuilderApi.PostSelectStep select(String... columns);
    }

    public interface IFromTransition {
        QueryBuilderApi.PostFromStep from(String table);
    }

    public interface IWhereTransition {
        QueryBuilderApi.PostWhereStep where(String expression);
    }

    public interface IGroupByTransition {
        QueryBuilderApi.PostGroupByStep groupBy(String column);
    }

    public interface IOrderByTransition {
        QueryBuilderApi.PostOrderByStep orderBy(String... columns);
    }

    public interface IOrderDirectionTransition {
        QueryBuilderApi.PostOrderDirectionStep asc();
        QueryBuilderApi.PostOrderDirectionStep desc();
    }

    public interface IBuildQueryTransformation {
        String build();
    }

    public static class InitialStep implements ISelectTransition {
        private  QueryBuilderImpl.Content content;

        public InitialStep(QueryBuilderImpl.Content _content) {
            content = _content;
        }

        @Override
        public QueryBuilderApi.PostSelectStep select(String... columns) {
            QueryBuilderImpl.Logic.selectTransitionSelect(content, columns);
            return new QueryBuilderApi.PostSelectStep(content);
        }

    }
    public static class PostSelectStep implements IFromTransition {
        private  QueryBuilderImpl.Content content;

        public PostSelectStep(QueryBuilderImpl.Content _content) {
            content = _content;
        }

        @Override
        public QueryBuilderApi.PostFromStep from(String table) {
            QueryBuilderImpl.Logic.fromTransitionFrom(content, table);
            return new QueryBuilderApi.PostFromStep(content);
        }

    }
    public static class PostFromStep implements IBuildQueryTransformation, IWhereTransition, IGroupByTransition, IOrderByTransition {
        private  QueryBuilderImpl.Content content;

        public PostFromStep(QueryBuilderImpl.Content _content) {
            content = _content;
        }

        @Override
        public String build() {
            return QueryBuilderImpl.Logic.buildQueryTransformationBuild(content);
        }

        @Override
        public QueryBuilderApi.PostWhereStep where(String expression) {
            QueryBuilderImpl.Logic.whereTransitionWhere(content, expression);
            return new QueryBuilderApi.PostWhereStep(content);
        }

        @Override
        public QueryBuilderApi.PostGroupByStep groupBy(String column) {
            QueryBuilderImpl.Logic.groupByTransitionGroupBy(content, column);
            return new QueryBuilderApi.PostGroupByStep(content);
        }

        @Override
        public QueryBuilderApi.PostOrderByStep orderBy(String... columns) {
            QueryBuilderImpl.Logic.orderByTransitionOrderBy(content, columns);
            return new QueryBuilderApi.PostOrderByStep(content);
        }

    }
    public static class PostWhereStep implements IBuildQueryTransformation, IGroupByTransition, IOrderByTransition {
        private  QueryBuilderImpl.Content content;

        public PostWhereStep(QueryBuilderImpl.Content _content) {
            content = _content;
        }

        @Override
        public String build() {
            return QueryBuilderImpl.Logic.buildQueryTransformationBuild(content);
        }

        @Override
        public QueryBuilderApi.PostGroupByStep groupBy(String column) {
            QueryBuilderImpl.Logic.groupByTransitionGroupBy(content, column);
            return new QueryBuilderApi.PostGroupByStep(content);
        }

        @Override
        public QueryBuilderApi.PostOrderByStep orderBy(String... columns) {
            QueryBuilderImpl.Logic.orderByTransitionOrderBy(content, columns);
            return new QueryBuilderApi.PostOrderByStep(content);
        }

    }
    public static class PostGroupByStep implements IBuildQueryTransformation, IOrderByTransition {
        private  QueryBuilderImpl.Content content;

        public PostGroupByStep(QueryBuilderImpl.Content _content) {
            content = _content;
        }

        @Override
        public String build() {
            return QueryBuilderImpl.Logic.buildQueryTransformationBuild(content);
        }

        @Override
        public QueryBuilderApi.PostOrderByStep orderBy(String... columns) {
            QueryBuilderImpl.Logic.orderByTransitionOrderBy(content, columns);
            return new QueryBuilderApi.PostOrderByStep(content);
        }

    }
    public static class PostOrderByStep implements IOrderDirectionTransition {
        private  QueryBuilderImpl.Content content;

        public PostOrderByStep(QueryBuilderImpl.Content _content) {
            content = _content;
        }

        @Override
        public QueryBuilderApi.PostOrderDirectionStep asc() {
            QueryBuilderImpl.Logic.orderDirectionTransitionAsc(content);
            return new QueryBuilderApi.PostOrderDirectionStep(content);
        }

        @Override
        public QueryBuilderApi.PostOrderDirectionStep desc() {
            QueryBuilderImpl.Logic.orderDirectionTransitionDesc(content);
            return new QueryBuilderApi.PostOrderDirectionStep(content);
        }

    }
    public static class PostOrderDirectionStep implements IBuildQueryTransformation {
        private  QueryBuilderImpl.Content content;

        public PostOrderDirectionStep(QueryBuilderImpl.Content _content) {
            content = _content;
        }

        @Override
        public String build() {
            return QueryBuilderImpl.Logic.buildQueryTransformationBuild(content);
        }

    }
}
