/*
Copyright @ 2017 Rushing Vise OU

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

package com.rushingvise.metagen.generator;

import com.rushingvise.metagen.generator.CodeModel.*;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.StringJoiner;

public class JavaCodeGenerator extends CodeGenerator {
    private final String mPackageName;

    public JavaCodeGenerator(String outputPath, CodeModel codeModel, String packageName) {
        super(outputPath, codeModel);
        mPackageName = packageName;
    }

    @Override
    public void generate() throws CodeGeneratorException {
        try {
            for (ClassModel classModel : mCodeModel.classes) {
                File outputFile = new File(mOutputPath, classModel.name + ".java");
                if (!outputFile.exists()) {
                    outputFile.createNewFile();
                }
                FileOutputStream outputStream = new FileOutputStream(outputFile);
                CodePrintWriter writer = new CodePrintWriter(outputStream);
                generateMainClass(classModel, writer);
            }
        } catch (IOException e) {
            throw new CodeGeneratorException(e);
        }
    }

    private void generateClass(JavaInstructionModelSerializer instructionModelSerializer, ClassModel mainClassModel, ClassModel classModel, CodePrintWriter writer) throws CodeGeneratorException {
        writer.block(createJavaClass(mainClassModel, classModel), () -> {
            for (FieldModel fieldModel : classModel.fieldModels) {
                writer.println(createJavaVisibility(fieldModel.visibility) + " " + createJavaField(classModel, fieldModel) + ";");
            }
            writer.println();
            for (ConstructorModel constructorModel : classModel.constructorModels) {
                writer.block(createJavaConstructor(classModel, constructorModel), () -> {
                    for (InstructionModel instructionModel : constructorModel.constructorBody) {
                        writer.println(instructionModel.accept(instructionModelSerializer) + ';');
                    }
                });
                writer.println();
            }
            for (MethodModel methodModel : classModel.methodModels) {
                writer.block(createJavaClassMethod(classModel, methodModel), () -> {
                    for (InstructionModel instructionModel : methodModel.methodBody) {
                        writer.println(instructionModel.accept(instructionModelSerializer) + ';');
                    }
                });
                writer.println();
            }

            if (mainClassModel != classModel) {
                if (classModel.interfaces.size() > 0) {
                    throw new CodeGeneratorException("Only main class can contain inner interfaces.");
                }
                if (classModel.classes.size() > 0) {
                    throw new CodeGeneratorException("Only main class can contain inner classes.");
                }
            }

            for (InterfaceModel interfaceModel : classModel.interfaces) {
                writer.block(createJavaInterface(interfaceModel), () -> {
                    for (MethodModel methodModel : interfaceModel.methodModels) {
                        writer.println(createJavaInterfaceMethod(classModel, methodModel) + ";");
                    }
                });
                writer.println();
            }

            for (ClassModel innerClass : classModel.classes) {
                generateClass(instructionModelSerializer, mainClassModel, innerClass, writer);
            }
        });
    }

    private void generateMainClass(ClassModel mainClassModel, CodePrintWriter writer) throws CodeGeneratorException {
        final JavaInstructionModelSerializer instructionModelSerializer = new JavaInstructionModelSerializer(mainClassModel);
        writer.println("// GENERATED BY METAGEN");
        writer.println();
        if (mPackageName != null) {
            writer.println("package " + mPackageName + ";");
            writer.println();
        }
        generateClass(instructionModelSerializer, mainClassModel, mainClassModel, writer);
    }

    private String createJavaInterface(InterfaceModel interfaceModel) {
        return createJavaVisibility(interfaceModel.visibility) + " interface " + interfaceModel.name;
    }

    private String createJavaClass(ClassModel containerClass, ClassModel classModel) {
        StringBuilder ret = new StringBuilder();
        ret.append(createJavaVisibility(classModel.visibility));
        ret.append(' ');
        if (classModel._static) {
            ret.append("static ");
        }
        ret.append("class ");
        ret.append(classModel.name);
        ret.append(' ');
        if (classModel.superClass != null) {
            ret.append("extends ");
            ret.append(createJavaType(containerClass, new TypeModel(classModel.superClass)));
        }
        if (classModel.implementedInterfaceModels.size() > 0) {
            StringJoiner interfaces = new StringJoiner(", ", "implements ", "");
            for (InterfaceModel interfaceModel : classModel.implementedInterfaceModels) {
                interfaces.add(interfaceModel.name);
            }
            ret.append(interfaces.toString());
        }
        return ret.toString();
    }

    private static String createJavaVisibility(Visibility visibility) {
        switch (visibility) {
            case PUBLIC:
            default:
                return "public";
            case PRIVATE:
                return "private";
            case PROTECTED:
                return "protected";
        }
    }

    private static String createJavaInterfaceMethod(ClassModel containerClass, MethodModel model) {
        StringBuilder ret = new StringBuilder();
        ret.append(createJavaType(containerClass, model.returnType));
        ret.append(' ');
        ret.append(model.name);
        StringJoiner arguments = new StringJoiner(", ", "(", ")");
        for (ArgumentModel argumentModel : model.argumentModels) {
            arguments.add(createJavaArgument(containerClass, argumentModel));
        }
        ret.append(arguments.toString());
        return ret.toString();
    }

    private static String createJavaClassMethod(ClassModel containerClass, MethodModel model) {
        StringBuilder ret = new StringBuilder();
        if (model.overrides) {
            ret.append("@Override\n");
        }
        ret.append(createJavaVisibility(model.visibility));
        ret.append(' ');
        if (model._static) {
            ret.append("static ");
        }
        ret.append(createJavaType(containerClass, model.returnType));
        ret.append(' ');
        ret.append(model.name);
        StringJoiner arguments = new StringJoiner(", ", "(", ")");
        for (ArgumentModel argumentModel : model.argumentModels) {
            arguments.add(createJavaArgument(containerClass, argumentModel));
        }
        ret.append(arguments.toString());
        return ret.toString();
    }

    private static String createJavaConstructor(ClassModel containerClass, ConstructorModel model) {
        StringBuilder ret = new StringBuilder();
        ret.append(createJavaVisibility(model.visibility));
        ret.append(' ');
        ret.append(model.classModel.name);
        StringJoiner arguments = new StringJoiner(", ", "(", ")");
        for (ArgumentModel argumentModel : model.argumentModels) {
            arguments.add(createJavaArgument(containerClass, argumentModel));
        }
        ret.append(arguments.toString());
        return ret.toString();
    }

    private static String createJavaArgument(ClassModel containerClass, ArgumentModel argumentModel) {
        StringBuilder ret = new StringBuilder();
        ret.append(createJavaType(containerClass, argumentModel.type));
        if (argumentModel.vararg) {
            ret.append("...");
        } else if (argumentModel.array) {
            ret.append("[]");
        }
        ret.append(' ');
        ret.append(argumentModel.name);
        return ret.toString();
    }

    private static String createJavaField(ClassModel containerClass, FieldModel fieldModel) {
        StringBuilder ret = new StringBuilder();
        ret.append(createJavaType(containerClass, fieldModel.type));
        ret.append(' ');
        ret.append(fieldModel.name);
        return ret.toString();
    }

    private static String createJavaType(ClassModel containerClass, TypeModel type) {
        if (type == TypeModel.TYPE_VOID) {
            return "void";
        } else if (type == TypeModel.TYPE_STRING) {
            return "String";
        } else if (type.name != null || containerClass == null) {
            return type.name;
        } else {
            if (containerClass.name.equals(type.classModel.containerClass.name)) {
                return type.classModel.name;
            } else {
                return type.classModel.containerClass.name + "." + type.classModel.name;
            }
        }
    }

    private static class JavaInstructionModelSerializer implements InstructionModelSerializer {
        private final ClassModel mMainClassModel;

        public JavaInstructionModelSerializer(ClassModel mainClassModel) {
            mMainClassModel = mainClassModel;
        }

        @Override
        public String visit(StringValueModel stringValueModel) {
            return "\"" + stringValueModel.toString() + "\"";
        }

        @Override
        public String visit(IntegerValueModel integerValueModel) {
            return integerValueModel.value.toString();
        }

        @Override
        public String visit(NullValueModel nullValueModel) {
            return "null";
        }

        @Override
        public String visit(VariableModel variableModel) {
            return variableModel.name;
        }

        @Override
        public String visit(DeclarationModel declarationModel) {
            return declarationModel.variable.type + " " + declarationModel.variable.name;
        }

        @Override
        public String visit(AssignmentModel assignmentModel) {
            return assignmentModel.leftValue.accept(this) + " = " + assignmentModel.rightValue.accept(this);
        }

        @Override
        public String visit(ReturnInstructionModel returnInstructionModel) {
            return "return " + returnInstructionModel.returnedStatement.accept(this);
        }

        @Override
        public String visit(MethodCallModel methodCallModel) {
            StringBuilder ret = new StringBuilder();
            if (methodCallModel.classInstance != null) {
                ret.append(methodCallModel.classInstance.containerClass.name).append('.');
                ret.append(methodCallModel.classInstance.name).append('.');
            } else if (methodCallModel.instance != null) {
                ret.append(methodCallModel.instance.name).append('.');
            }
            ret.append(methodCallModel.methodName);
            StringJoiner arguments = new StringJoiner(", ", "(", ")");
            for (RValueModel rValueModel : methodCallModel.parameters) {
                arguments.add(rValueModel.accept(this));
            }
            ret.append(arguments.toString());
            return ret.toString();
        }

        @Override
        public String visit(AllocationModel allocationModel) {
            StringBuilder ret = new StringBuilder();
            ret.append("new ");
            ret.append(createJavaType(mMainClassModel, allocationModel.type));
            StringJoiner arguments = new StringJoiner(", ", "(", ")");
            for (RValueModel rValueModel : allocationModel.parameters) {
                arguments.add(rValueModel.accept(this));
            }
            ret.append(arguments.toString());
            return ret.toString();
        }

        @Override
        public String visit(SuperCallModel superCallModel) {
            StringBuilder ret = new StringBuilder();
            ret.append("super");
            StringJoiner arguments = new StringJoiner(", ", "(", ")");
            for (RValueModel rValueModel : superCallModel.parameters) {
                arguments.add(rValueModel.accept(this));
            }
            ret.append(arguments.toString());
            return ret.toString();
        }
    }
}
