// GENERATED BY METAGEN
#pragma once

#include <memory>
#include <string>
#include <vector>
#include "ExpressionBuilderApi.h"
#include "ExpressionBuilderImpl.h"

namespace sql {

class ExpressionBuilder : public ExpressionBuilderApi::ExpressionStep {

    public:
    ExpressionBuilder();
};
}

