// GENERATED BY METAGEN
#pragma once

#include <memory>
#include <string>
#include <vector>
#include "QueryBuilderImpl.h"

namespace sql {

class QueryBuilderApi  {
    public:
    class ISelectTransition;
    class IFromTransition;
    class IWhereTransition;
    class IGroupByTransition;
    class IOrderByTransition;
    class IOrderDirectionTransition;
    class IBuildQueryTransformation;
    class InitialStep;
    class PostSelectStep;
    class PostFromStep;
    class PostWhereStep;
    class PostGroupByStep;
    class PostOrderByStep;
    class PostOrderDirectionStep;

    class ISelectTransition {
        virtual QueryBuilderApi::PostSelectStep select(std::vector<std::string> columns) =0;
    };

    class IFromTransition {
        virtual QueryBuilderApi::PostFromStep from(std::string table) =0;
    };

    class IWhereTransition {
        virtual QueryBuilderApi::PostWhereStep where(std::string expression) =0;
    };

    class IGroupByTransition {
        virtual QueryBuilderApi::PostGroupByStep groupBy(std::string column) =0;
    };

    class IOrderByTransition {
        virtual QueryBuilderApi::PostOrderByStep orderBy(std::vector<std::string> columns) =0;
    };

    class IOrderDirectionTransition {
        virtual QueryBuilderApi::PostOrderDirectionStep asc() =0;
        virtual QueryBuilderApi::PostOrderDirectionStep desc() =0;
    };

    class IBuildQueryTransformation {
        virtual std::string build() =0;
    };

    class InitialStep : public ISelectTransition {
        private:
         QueryBuilderImpl::Content content;

        public:
        InitialStep(QueryBuilderImpl::Content _content);
        QueryBuilderApi::PostSelectStep select(std::vector<std::string> columns) override;
    };
    class PostSelectStep : public IFromTransition {
        private:
         QueryBuilderImpl::Content content;

        public:
        PostSelectStep(QueryBuilderImpl::Content _content);
        QueryBuilderApi::PostFromStep from(std::string table) override;
    };
    class PostFromStep : public IBuildQueryTransformation, public IWhereTransition, public IGroupByTransition, public IOrderByTransition {
        private:
         QueryBuilderImpl::Content content;

        public:
        PostFromStep(QueryBuilderImpl::Content _content);
        std::string build() override;
        QueryBuilderApi::PostWhereStep where(std::string expression) override;
        QueryBuilderApi::PostGroupByStep groupBy(std::string column) override;
        QueryBuilderApi::PostOrderByStep orderBy(std::vector<std::string> columns) override;
    };
    class PostWhereStep : public IBuildQueryTransformation, public IGroupByTransition, public IOrderByTransition {
        private:
         QueryBuilderImpl::Content content;

        public:
        PostWhereStep(QueryBuilderImpl::Content _content);
        std::string build() override;
        QueryBuilderApi::PostGroupByStep groupBy(std::string column) override;
        QueryBuilderApi::PostOrderByStep orderBy(std::vector<std::string> columns) override;
    };
    class PostGroupByStep : public IBuildQueryTransformation, public IOrderByTransition {
        private:
         QueryBuilderImpl::Content content;

        public:
        PostGroupByStep(QueryBuilderImpl::Content _content);
        std::string build() override;
        QueryBuilderApi::PostOrderByStep orderBy(std::vector<std::string> columns) override;
    };
    class PostOrderByStep : public IOrderDirectionTransition {
        private:
         QueryBuilderImpl::Content content;

        public:
        PostOrderByStep(QueryBuilderImpl::Content _content);
        QueryBuilderApi::PostOrderDirectionStep asc() override;
        QueryBuilderApi::PostOrderDirectionStep desc() override;
    };
    class PostOrderDirectionStep : public IBuildQueryTransformation {
        private:
         QueryBuilderImpl::Content content;

        public:
        PostOrderDirectionStep(QueryBuilderImpl::Content _content);
        std::string build() override;
    };
};
}

