// GENERATED BY METAGEN
#pragma once

#include <memory>
#include <string>
#include <vector>
#include "QueryBuilderApi.h"
#include "QueryBuilderImpl.h"

namespace sql {

class QueryBuilder : public QueryBuilderApi::InitialStep {

    public:
    QueryBuilder() : QueryBuilderApi::InitialStep(QueryBuilderImpl::Content()) {
    }

};
}

